services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CRON=0 10 * * 2

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always