name: Build and Release Deno Executable

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Deno executable
        run: deno task build

      - name: Upload executable to Release
        uses: softprops/action-gh-release@v2
        with:
          files: berichtsheft
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"

